use_frameworks!

platform :ios, '9.0'

target 'ZUJIANNetworking_Example' do
  pod 'ZUJIANNetworking', :path => '../'

  target 'ZUJIANNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
